# Generated by Django 4.2.19 on 2025-03-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_alter_pongroom_id_alter_pongroom_player1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
